### ISSUE TITLE
Getting NPE with /slot build <design> <name>

### ISSUE THREAD

**Issue by TNTUP** [DarkBlade12/ItemSlotMachine#4]
[16:24:26] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'slot' in plugin ItemSlotMachine v1.3.2
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[craftbukkit.jar:git-Spigot-e497721-96d09e3]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[craftbukkit.jar:git-Spigot-e497721-96d09e3]
	at org.bukkit.craftbukkit.v1_8_R1.CraftServer.dispatchCommand(CraftServer.java:645) ~[craftbukkit.jar:git-Spigot-e497721-96d09e3]
	at net.minecraft.server.v1_8_R1.PlayerConnection.handleCommand(PlayerConnection.java:1115) [craftbukkit.jar:git-Spigot-e497721-96d09e3]
	at net.minecraft.server.v1_8_R1.PlayerConnection.a(PlayerConnection.java:950) [craftbukkit.jar:git-Spigot-e497721-96d09e3]
	at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(PacketPlayInChat.java:26) [craftbukkit.jar:git-Spigot-e497721-96d09e3]
	at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(PacketPlayInChat.java:53) [craftbukkit.jar:git-Spigot-e497721-96d09e3]
	at net.minecraft.server.v1_8_R1.PacketHandleTask.run(SourceFile:13) [craftbukkit.jar:git-Spigot-e497721-96d09e3]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) [?:1.7.0_65]
	at java.util.concurrent.FutureTask.run(FutureTask.java:262) [?:1.7.0_65]
	at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:683) [craftbukkit.jar:git-Spigot-e497721-96d09e3]
	at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316) [craftbukkit.jar:git-Spigot-e497721-96d09e3]
	at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:623) [craftbukkit.jar:git-Spigot-e497721-96d09e3]
	at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:526) [craftbukkit.jar:git-Spigot-e497721-96d09e3]
	at java.lang.Thread.run(Thread.java:745) [?:1.7.0_65]
Caused by: java.lang.NullPointerException
	at java.lang.String.replace(String.java:2180) ~[?:1.7.0_65]
	at com.darkblade12.itemslotmachine.message.MessageManager.slot_machine_building_failure(MessageManager.java:551) ~[?:?]
	at com.darkblade12.itemslotmachine.command.slot.BuildCommand.execute(BuildCommand.java:35) ~[?:?]
	at com.darkblade12.itemslotmachine.command.CommandHandler.onCommand(CommandHandler.java:53) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[craftbukkit.jar:git-Spigot-e497721-96d09e3]
	... 14 more

Does it has to include itemframes and sign? If so they're present, but what else idk whats is causing the error

**Comment by DarkBlade12** [comment]
It seems like you're missing the *slot_machine_building_failure* message in your language file! Try to add ```slot_machine_building_failure=&cThe slot machine building failed! Cause: &6<cause>``` to your language file! Besides this error might happen because there's not enough space for the slot machine.

**Comment by TNTUP** [comment]
Huh... I haven't touched the language file yet so how it can be missing since its from the plugin (generated new files)

Ill try adding it, but theres space for building it though...

**Comment by TNTUP** [comment]
I checked the file and its there.. Idk whats wrong what I did though I did the same steps with the stable one on BukkitDev. Will retry setting a new one

**Comment by DarkBlade12** [comment]
Have you tried to set up and build another design? Or did you try out building one in the air?

**Comment by TNTUP** [comment]
I tried building 4 in different ways no luck, even tried another design, still failing. Ill try one without plugins (test server) to see it if work, if so, must be a plugin preventing it, gotta do tests

**Comment by DarkBlade12** [comment]
If this still doesn't work, you can send me your designs/setup in a compressed file via e-mail (stefan.xd@gmx.de) for me to try that out!

**Comment by TNTUP** [comment]
no updates since, dropping using this plugin since it doesn't work on my side doign the same steps as before. I'm closing it, giving up waiting

**Comment by TNTUP** [comment]
Any news on latest updates? Doesn't work in 1.8.3

**Comment by DarkBlade12** [comment]
Just tested the current version on my test server and it still works fine for me. (generation and playing) I'm sorry but I can't really help you if I don't know what the issue exactly is :/

**Comment by TNTUP** [comment]
on Spigot 1.8.3?

**Comment by DarkBlade12** [comment]
Yes, I just ran the Spigot updater and took the new version and used the file on GitHub in my plugin folder, just to be safe not too use another version you don't have. Then I ran the server and tried to build a slot machine and play on it and everything worked fine.

**Comment by TNTUP** [comment]
huh, just tried on a test server it works nicely on the latest 1.8.3 spigot, last time on 1.8/3 it didn't work... Leeme try it on my productive server

**Comment by DarkBlade12** [comment]
Hmm, so it does work if you enable the item pot in the template or what?

**Comment by TNTUP** [comment]
Yep, turning the item pot on it works. Before with 1.7.10's it was fine and item pot was off.

**Comment by DarkBlade12** [comment]
Okay, thanks for the info, I'll investigate this and report back if i found a fix!

**Comment by TNTUP** [comment]
No problem :)

**Comment by DarkBlade12** [comment]
Just fixed this issue with the recent commit and added a new release here: https://github.com/DarkBlade12/ItemSlotMachine/releases/tag/1.3.3
