### ISSUE TITLE
Getting NPE when increating lock machine time

### ISSUE THREAD

**Issue by TNTUP** [DarkBlade12/ItemSlotMachine#6]
Hey, I noticed since when I increased the lock time, i'm getting this kind of error:

[17:54:22] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to ItemSlotMachine v1.3.2
org.bukkit.event.EventException
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot.jar:git-Spigot-044d928-e8c6403]
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-044d928-e8c6403]
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-044d928-e8c6403]
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-044d928-e8c6403]
    at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:227) [spigot.jar:git-Spigot-044d928-e8c6403]
    at net.minecraft.server.v1_8_R3.PlayerInteractManager.interact(PlayerInteractManager.java:463) [spigot.jar:git-Spigot-044d928-e8c6403]
    at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:736) [spigot.jar:git-Spigot-044d928-e8c6403]
    at net.minecraft.server.v1_8_R3.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:52) [spigot.jar:git-Spigot-044d928-e8c6403]
    at net.minecraft.server.v1_8_R3.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:1) [spigot.jar:git-Spigot-044d928-e8c6403]
    at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-044d928-e8c6403]
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) [?:1.7.0_75]
    at java.util.concurrent.FutureTask.run(FutureTask.java:262) [?:1.7.0_75]
    at net.minecraft.server.v1_8_R3.SystemUtils.a(SystemUtils.java:19) [spigot.jar:git-Spigot-044d928-e8c6403]
    at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:718) [spigot.jar:git-Spigot-044d928-e8c6403]
    at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:367) [spigot.jar:git-Spigot-044d928-e8c6403]
    at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:657) [spigot.jar:git-Spigot-044d928-e8c6403]
    at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:560) [spigot.jar:git-Spigot-044d928-e8c6403]
    at java.lang.Thread.run(Thread.java:745) [?:1.7.0_75]
Caused by: java.lang.NullPointerException
    at java.lang.String.replace(String.java:2180) ~[?:1.7.0_75]
    at com.darkblade12.itemslotmachine.message.MessageManager.slot_machine_locked(MessageManager.java:516) ~[?:?]
    at com.darkblade12.itemslotmachine.slotmachine.SlotMachineManager.onPlayerInteract(SlotMachineManager.java:311) ~[?:?]
    at sun.reflect.GeneratedMethodAccessor270.invoke(Unknown Source) ~[?:?]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_75]
    at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_75]
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-044d928-e8c6403]
    ... 17 more

I have set it to 250 (2 minutes 30 seconds) 

Still not updated to the latest dev build, I haven't time or forgot to update it. 

First, I'll try this one you fixed last week. Then I'll report it back if it still occurs.

**Comment by TNTUP** [comment]
I'll check with this build if it fixes it, then closing. Sorry if I waste your time :x:

**Comment by DarkBlade12** [comment]
I don't think that the current version fixes this issue. Could you tell me your skype name, in order to communicate faster?
